### ISSUE TITLE
Adding IP to non-existing Interface

### ISSUE THREAD

**Issue by sygilber** [IBM-Security/ibmsecurity#122]
If one mistakenly tries adding an IP address to a non-existing Interface the python code returns an error but not what may be expected. The following code if inserted into testisam.py:

```
# Create a user credential for ISAM appliance
u = ApplianceUser(username="admin@local", password="admin")
# Create an ISAM appliance with above credential
isam_server = ISAMAppliance(hostname="if1ipAddress user=u, lmi_port=443)
p(ibmsecurity.isam.base.network.interfaces_ipv4.add(isamAppliance=isam_server, allowManagement=False, enabled=True, vlanId=None, label="1.2", address="if2ipAddress", maskOrPrefix="24"))
```
Will produces the following trace (Note that Interface "1.2" does not exists on the target Appliance):

```
 [2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.user.applianceuser] [__init__():9] Creating a user
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.user.user] [__init__():8] Creating a user
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.isamappliance] [__init__():14] Creating an ISAMAppliance
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [__init__():50] Creating an IBMAppliance
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_request():599] Request: GET /core/sys/versions desc=Retrieving version
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():31] *** Retrieving version ***
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():100] Checking for minimum version: None.
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():116] Checking for one of required modules: None.
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():133] Warnings: []
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():309] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():314] Input Data: {}
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():36] Suppressing SSL Warnings.
[2018-11-19 14:49:54,503] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():25] Issuing request to: https://if1ipAddress:443/core/sys/versions
[2018-11-19 14:49:54,653] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():71] Status Code: 200
[2018-11-19 14:49:54,654] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():73] Text: {"firmware_label":"isam_9.0.5.0_20180606-2319","firmware_build":"20180606-2319","firmware_version":"9.0.5.0","product_description":"IBM Security Access Manager","deployment_model":"Appliance","product_name":"isam"}
[2018-11-19 14:49:54,654] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_response():603] Response: 0
[2018-11-19 14:49:54,654] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_request():599] Request: GET /setup_complete desc=Get Setup Complete Settings
[2018-11-19 14:49:54,654] [PID:49872 TID:139628044715840] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():31] *** Get Setup Complete Settings ***
[2018-11-19 14:49:54,654] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():100] Checking for minimum version: None.
[2018-11-19 14:49:54,654] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():116] Checking for one of required modules: None.
[2018-11-19 14:49:54,654] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():133] Warnings: []
[2018-11-19 14:49:54,654] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():309] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}
[2018-11-19 14:49:54,654] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():314] Input Data: {}
[2018-11-19 14:49:54,654] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():36] Suppressing SSL Warnings.
[2018-11-19 14:49:54,654] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():25] Issuing request to: https://if1ipAddress:443/setup_complete
[2018-11-19 14:49:54,773] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():71] Status Code: 200
[2018-11-19 14:49:54,773] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():73] Text: { "configured": true}
[2018-11-19 14:49:54,774] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_response():603] Response: 0
[2018-11-19 14:49:54,774] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_request():599] Request: GET /isam/capabilities/v1 desc=Retrieving activations
[2018-11-19 14:49:54,774] [PID:49872 TID:139628044715840] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():31] *** Retrieving activations ***
[2018-11-19 14:49:54,774] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():100] Checking for minimum version: None.
[2018-11-19 14:49:54,774] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():116] Checking for one of required modules: None.
[2018-11-19 14:49:54,774] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():133] Warnings: []
[2018-11-19 14:49:54,774] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():309] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}
[2018-11-19 14:49:54,774] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():314] Input Data: {}
[2018-11-19 14:49:54,774] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():36] Suppressing SSL Warnings.
[2018-11-19 14:49:54,774] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():25] Issuing request to: https://if1ipAddress:443/isam/capabilities/v1
[2018-11-19 14:49:54,912] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():71] Status Code: 200
[2018-11-19 14:49:54,912] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():73] Text: []
[2018-11-19 14:49:54,912] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_response():603] Response: 0
[2018-11-19 14:49:54,912] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_request():599] Request: GET /net/ifaces desc=Retrieving all interfaces
[2018-11-19 14:49:54,912] [PID:49872 TID:139628044715840] [INFO] [ibmsecurity.appliance.ibmappliance] [_log_desc():31] *** Retrieving all interfaces ***
[2018-11-19 14:49:54,912] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():100] Checking for minimum version: None.
[2018-11-19 14:49:54,912] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():116] Checking for one of required modules: None.
[2018-11-19 14:49:54,912] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_warnings():133] Warnings: []
[2018-11-19 14:49:54,912] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():309] Headers are: {'Content-type': 'application/json', 'Accept': 'application/json'}
[2018-11-19 14:49:54,913] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_invoke_request():314] Input Data: {}
[2018-11-19 14:49:54,913] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_suppress_ssl_warning():36] Suppressing SSL Warnings.
[2018-11-19 14:49:54,913] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_url():25] Issuing request to: https://if1ipAddress:443/net/ifaces
[2018-11-19 14:49:55,077] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():71] Status Code: 200
[2018-11-19 14:49:55,078] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_process_response():73] Text: {"interfaces":[{"ipv4":{"dhcp":{"enabled":false,"allowManagement":true,"providesDefaultRoute":true,"routeMetric":null},"addresses":[{"address":"if1ipAddress","maskOrPrefix":"24","broadcastAddress":null,"allowManagement":true,"enabled":true,"uuid":"cac0b1ca-7442-4c8d-a674-4cf977a8ac1e","objType":"ipv4Address"}]},"ipv6":{"dhcp":{"enabled":true,"allowManagement":false},"addresses":[]},"name":null,"label":"1.1","enabled":true,"type":"physical","vlanId":null,"bondingMode":"","bondedTo":null,"uuid":"b702f799-c305-4439-8835-4e51c9b6d16b","objType":"interface","comment":null},{"ipv4":{"dhcp":{"enabled":false,"allowManagement":false,"providesDefaultRoute":false,"routeMetric":null},"addresses":[]},"ipv6":{"dhcp":{"enabled":false,"allowManagement":false},"addresses":[]},"name":null,"label":"loopback","enabled":true,"type":"loopback","vlanId":null,"bondingMode":"","bondedTo":null,"uuid":"71801cf1-5a16-4e4d-a05f-106c3ebd0ae6","objType":"interface","comment":null}]}
[2018-11-19 14:49:55,078] [PID:49872 TID:139628044715840] [DEBUG] [ibmsecurity.appliance.ibmappliance] [_log_response():603] Response: 0
Traceback (most recent call last):
  File "./test.py", line 85, in <module>
    p(ibmsecurity.isam.base.network.interfaces_ipv4.add(isamAppliance=isam_server, allowManagement=False, enabled=True, vlanId=None, label="1.2", address="if2ipAddress", maskOrPrefix="24"))
  File "/home/sygilber/.local/lib/python2.7/site-packages/ibmsecurity/src/ibmsecurity/ibmsecurity/isam/base/network/interfaces_ipv4.py", line 25, in add
    ret_obj['ipv4']['overrideSubnetChecking'] = overrideSubnetChecking
TypeError: 'NoneType' object has no attribute '__getitem__'

```
It could be considered confusing to get a TypeError here but the reason is that the error handling code in the add() method is not taking action if the call to ‘ret_obj = ibmsecurity.isam.base.network.interfaces._get_interface’ returns None, so the execution continues and fails later on with some obscure message.

```
    """
    Adding an IPv4 address to an interface
    """
    add_needed = True
    ret_obj = {}
    if force is False:
        ret_obj = ibmsecurity.isam.base.network.interfaces._get_interface(isamAppliance, label, vlanId)
        if ret_obj is not None:
            del ret_obj['objType']
            del ret_obj['type']
            for addr in ret_obj['ipv4']['addresses']:
                if addr['address'] == address:
                    add_needed = False

```
To make the error handling behavior more clear for the user, shouln’t we take care to abort execution in the "add()" method as soon as we are finding out that we are attempting to add an IP to an Interface that do not exist ?

Open to comments before considering a fix for this. issue

**Comment by ram-ibm** [comment]
Code merged.
